//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFly.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.FlightInfoes = new HashSet<FlightInfo>();
            this.FlightInfoes1 = new HashSet<FlightInfo>();
            this.FlightInfoes2 = new HashSet<FlightInfo>();
            this.FlightInfoes3 = new HashSet<FlightInfo>();
            this.FlightInfoes4 = new HashSet<FlightInfo>();
            this.FlightInfoes5 = new HashSet<FlightInfo>();
            this.FlightInfoes6 = new HashSet<FlightInfo>();
        }

        [Required]
        [Display(Name = "Employee ID")]
        [DataType(DataType.Text)]
        public string EmployeeID { get; set; }

        [Required]
        [Display(Name = "Email Address")]
        [DataType(DataType.EmailAddress)]
        public string E_Email { get; set; }

        [Display(Name = "Profile Photo")]
        [DataType(DataType.ImageUrl)]
        public string E_Photos { get; set; }
        public HttpPostedFileBase E_PhotoFile { get; set; }

        [Required]
        [Display(Name = "Name")]
        [DataType(DataType.Text)]
        public string E_Name { get; set; }

        [Required]
        [Display(Name = "Age")]
        [DataType(DataType.Text)]
        public int E_Age { get; set; }

        [Required]
        [Display(Name = "Contact No.")]
        [DataType(DataType.PhoneNumber)]
        public string E_ContactNo { get; set; }

        [Required]
        [Display(Name = "Designation")]
        [DataType(DataType.Text)]
        public string E_Designation { get; set; }

        [Required]
        [Display(Name = "Duty Status")]
        [DataType(DataType.Text)]
        public string DutyStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightInfo> FlightInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightInfo> FlightInfoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightInfo> FlightInfoes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightInfo> FlightInfoes3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightInfo> FlightInfoes4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightInfo> FlightInfoes5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightInfo> FlightInfoes6 { get; set; }
    }
}
