//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFly.Models
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class FlightInfo
	{
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public FlightInfo()
		{
			this.Feedbacks = new HashSet<Feedback>();
			this.PassengerFlights = new HashSet<PassengerFlight>();
			this.CargoFlights = new HashSet<CargoFlight>();
		}

		[Required]
		[Display(Name = "Flight ID")]
		[DataType(DataType.Text)]
		public string FlightID { get; set; }

		[Required]
		[Display(Name = "Aircraft ID")]
		[DataType(DataType.Text)]
		public string AirCraftID { get; set; }

		[Required]
		[Display(Name = "Depurture City")]
		[DataType(DataType.Text)]
		public string From1 { get; set; }

		[Required]
		[Display(Name = "Destination City")]
		[DataType(DataType.Text)]
		public string To1 { get; set; }

		[Required]
		[Display(Name = "Depurture Date")]
		[DataType(DataType.Date)]
		public System.DateTime DepartureDate { get; set; }

		[Required]
		[Display(Name = "Arrival Date")]
		[DataType(DataType.Date)]
		public System.DateTime ArrivalDate { get; set; }

		[Required]
		[Display(Name = "Flight Class")]
		[DataType(DataType.Text)]
		public string ClassType { get; set; }

		[Required]
		[Display(Name = "First Pilot")]
		[DataType(DataType.Text)]
		public string Pilot1 { get; set; }

		[Required]
		[Display(Name = "Second Pilot")]
		[DataType(DataType.Text)]
		public string Pilot2 { get; set; }

		[Display(Name = "First Cabin Crew")]
		[DataType(DataType.Text)]
		public string CabinCrew1 { get; set; }

		[Display(Name = "Second Cabin Crew")]
		[DataType(DataType.Text)]
		public string CabinCrew2 { get; set; }

		[Display(Name = "Third Cabin Crew")]
		[DataType(DataType.Text)]
		public string CabinCrew3 { get; set; }

		[Required]
		[Display(Name = "First Assistant")]
		[DataType(DataType.Text)]
		public string Assistant1 { get; set; }

		[Required]
		[Display(Name = "Second Assistant")]
		[DataType(DataType.Text)]
		public string Assistant2 { get; set; }

		[Required]
		[Display(Name = "Flight Fare")]
		[DataType(DataType.Currency)]
		public int Fare { get; set; }

		[Required]
		[Display(Name = "Available Seats")]
		[DataType(DataType.Text)]
		public Nullable<int> AvailableSeats { get; set; }

		[Display(Name = "Booked Seats")]
		[DataType(DataType.Text)]
		public string BookedSeats { get; set; }


		[Required]
		[Display(Name = "Flight Type")]
		[DataType(DataType.Text)]
		public string FlightType { get; set; }


		public List<String> CityList { get; set; }


		public List<Employee> Pilot1List { get; set; }
		public List<Employee> Pilot2List { get; set; }


		public List<Employee> CabinCrew1List { get; set; }
		public List<Employee> CabinCrew2List { get; set; }
		public List<Employee> CabinCrew3List { get; set; }


		public List<Employee> Assistant1List { get; set; }
		public List<Employee> Assistant2List { get; set; }




		public virtual AircraftInfo AircraftInfo { get; set; }
		public virtual Employee Employee { get; set; }
		public virtual Employee Employee1 { get; set; }
		public virtual Employee Employee2 { get; set; }
		public virtual Employee Employee3 { get; set; }
		public virtual Employee Employee4 { get; set; }
		public virtual Employee Employee5 { get; set; }
		public virtual Employee Employee6 { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<Feedback> Feedbacks { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<PassengerFlight> PassengerFlights { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<CargoFlight> CargoFlights { get; set; }
	}
}
