//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFly.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membership
    {
        public string S_UserID { get; set; }
        public string MemberStatus { get; set; }
        public int Point { get; set; }
    
        public virtual SingleUserLog SingleUserLog { get; set; }
    }
}
