//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFly.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassengerFlight
    {
        public string FlightID { get; set; }
        public string S_UserID { get; set; }
        public Nullable<int> NoOfSeats { get; set; }
        public string SeatNumbers { get; set; }
        public string HotelID { get; set; }
        public Nullable<int> TotalHotelRent { get; set; }
        public int TotalFlightFare { get; set; }
        public string PackageID { get; set; }
    
        public virtual FlightInfo FlightInfo { get; set; }
        public virtual HotelInfo HotelInfo { get; set; }
        public virtual SingleUserLog SingleUserLog { get; set; }
        public virtual PackageInfo PackageInfo { get; set; }
    }
}
